### ISSUE TITLE
你的项目进不去

### ISSUE THREAD

**Issue by Hi-PWC** [zhangyao1990/elegant-admin#1]
本地运行提示：你所访问的资源不存在！
点击你的在线预览提示：请求失败！

**Comment by Hi-PWC** [comment]
我的技术其实没有多棒，只是想体验一下你的框架，但是出现了以下问题所以想反馈以下，抱歉哈 :)

**Comment by zhangyao1990** [comment]
fastmock挂了，现在改用mock，可以预览了.
