### ISSUE TITLE
关于protable的指教

### ISSUE THREAD

**Issue by shuerchoi** [zhangyao1990/elegant-admin#4]
大佬，我也在使用geekerAdmin的protable
在使用过程中 发现vue升级后(3.4.21以上) protable的数据无法正常渲染
但是我看你的vue版本升级后，表格是没问题的
不知道你升级的过程中有没有遇到这个问题，是如何解决的？
烦请指教，十分感谢！

**Comment by zhangyao1990** [comment]
我这边没有碰到这个问题,有报错吗？
