### ISSUE TITLE
打包build没有遇到问题吗，我这边能运行，但是执行pnpm build:test 有问题

### ISSUE THREAD

**Issue by luojiwen** [zhangyao1990/elegant-admin#5]

**Comment by zhangyao1990** [comment]
什么问题，贴个图，目测是代码格式问题 。。

**Comment by luojiwen** [comment]
> 什么问题，贴个图，目标测是代码格式问题。

咦，图片有贴图的，我再重新来一次，编译的时候出现这个问题
(base) luojiwen@luojiwendeMacBook-Pro elegant-admin % pnpm build:test

> elegant-admin@1.0.1 build:test /Users/luojiwen/Documents/classify/workspace/project/person/LJW/front-web/elegant-admin
> vue-tsc && vite build --mode test

src/components/FormDesign/core/components/designer/src/modules/editContainer/editScreenContainer.vue:17:92 - error TS2345: Argument of type 'Ref<{ align: string; addEventListener: { <K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDivElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | ... 1 more ... | undefin...' is not assignable to parameter of type 'Ref<HTMLDivElement | null>'.
  Type '{ align: string; addEventListener: { <K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDivElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | ... 1 more ... | undefined):...' is not assignable to type 'HTMLDivElement | null'.
    Type '{ align: string; addEventListener: { <K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDivElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | ... 1 more ... | undefined):...' is not assignable to type 'HTMLDivElement'.
      Types of property 'offsetParent' are incompatible.
        Type '{ readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: ...; readonly length: number; item: (nameOrIndex?: string | undefined) => Element | ... 1 m...' is not assignable to type 'Element | null'.

17 const { handleElementDragStart, handleElementDrag, handleElementDragEnd } = useElementDrag(editScreenContainerRef)
                                                                                              ~~~~~~~~~~~~~~~~~~~~~~

src/components/FormDesign/core/components/designer/src/modules/editContainer/editScreenContainer.vue:18:42 - error TS2345: Argument of type 'Ref<{ align: string; addEventListener: { <K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDivElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | ... 1 more ... | undefin...' is not assignable to parameter of type 'MaybeComputedElementRef<MaybeElement>'.
  Type 'Ref<{ align: string; addEventListener: { <K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDivElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | ... 1 more ... | undefin...' is not assignable to type 'Ref<MaybeElement>'.
    Type '{ align: string; addEventListener: { <K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDivElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | ... 1 more ... | undefined):...' is not assignable to type 'MaybeElement'.
      Type '{ align: string; addEventListener: { <K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDivElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | ... 1 more ... | undefined):...' is not assignable to type 'MaybeElement'.
        Type '{ align: string; addEventListener: { <K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDivElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | ... 1 more ... | undefined):...' is not assignable to type 'HTMLElement'.
          Types of property 'offsetParent' are incompatible.
            Type '{ readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: ...; readonly length: number; item: (nameOrIndex?: string | undefined) => Element | ... 1 m...' is not assignable to type 'Element | null'.

18 const { width, height } = useElementSize(editScreenContainerRef)
                                            ~~~~~~~~~~~~~~~~~~~~~~

src/components/FormDesign/core/components/designer/src/modules/editContainer/editScreenContainer.vue:19:52 - error TS2345: Argument of type 'Ref<{ align: string; addEventListener: { <K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDivElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | ... 1 more ... | undefin...' is not assignable to parameter of type 'Ref<HTMLDivElement | null>'.

19 const { canvasScale, handleZoom } = useElementZoom(draggableElRef)
                                                      ~~~~~~~~~~~~~~

src/components/FormDesign/core/components/designer/src/modules/editContainer/editScreenContainer.vue:98:19 - error TS2345: Argument of type 'Ref<{ align: string; addEventListener: { <K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDivElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | ... 1 more ... | undefin...' is not assignable to parameter of type 'MaybeComputedElementRef<MaybeElement> | MaybeComputedElementRef<MaybeElement>[]'.
  Type 'Ref<{ align: string; addEventListener: { <K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDivElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | ... 1 more ... | undefin...' is not assignable to type 'Ref<MaybeElement>'.

98 useResizeObserver(editScreenContainerRef, ([{ contentRect }]) => {
                     ~~~~~~~~~~~~~~~~~~~~~~

src/components/ProTable/index.vue:130:52 - error TS2345: Argument of type '{ type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; label?: string | undefined; ... 12 more ...; xl?: { ...; } | undefined; } | undefined; ... 46 more ...; filterOpened?: boolean | undefined; }[]' is not assignable to parameter of type 'ColumnProps<any>[]'.
  Type '{ type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; label?: string | undefined; ... 12 more ...; xl?: { ...; } | undefined; } | undefined; ... 46 more ...; filterOpened?: boolean | undefined; }' is not assignable to type 'ColumnProps<any>'.
    Types of property 'showOverflowTooltip' are incompatible.
      Type 'boolean | { transition?: string | undefined; effect?: string | undefined; offset?: number | undefined; popperClass?: EpPropMergeType<(new (...args: any[]) => string | { [x: string]: boolean; } | (string | { ...; } | (string | ... 1 more ... | (string | ... 1 more ... | (string | ... 1 more ... | (string | ... 1 more...' is not assignable to type 'boolean | Partial<Pick<ElTooltipProps, "transition" | "effect" | "offset" | "popperClass" | "appendTo" | "showArrow" | "enterable" | "placement" | "popperOptions" | "showAfter" | "hideAfter">> | undefined'.
        Type '{ transition?: string | undefined; effect?: string | undefined; offset?: number | undefined; popperClass?: EpPropMergeType<(new (...args: any[]) => string | { [x: string]: boolean; } | (string | { [x: string]: boolean; } | (string | ... 1 more ... | (string | ... 1 more ... | (string | ... 1 more ... | (string | ......' is not assignable to type 'boolean | Partial<Pick<ElTooltipProps, "transition" | "effect" | "offset" | "popperClass" | "appendTo" | "showArrow" | "enterable" | "placement" | "popperOptions" | "showAfter" | "hideAfter">> | undefined'.
          Type '{ transition?: string | undefined; effect?: string | undefined; offset?: number | undefined; popperClass?: EpPropMergeType<(new (...args: any[]) => string | { [x: string]: boolean; } | (string | { [x: string]: boolean; } | (string | ... 1 more ... | (string | ... 1 more ... | (string | ... 1 more ... | (string | ......' is not assignable to type 'Partial<Pick<ElTooltipProps, "transition" | "effect" | "offset" | "popperClass" | "appendTo" | "showArrow" | "enterable" | "placement" | "popperOptions" | "showAfter" | "hideAfter">>'.
            Types of property 'appendTo' are incompatible.
              Type 'string | { accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 290 more ...; focus: (options?: FocusOptions | undefined) => void; } | undefined' is not assignable to type 'EpPropMergeType<(new (...args: any[]) => string | HTMLElement) | (() => string | HTMLElement) | ((new (...args: any[]) => string | HTMLElement) | (() => string | HTMLElement))[], unknown, unknown> | undefined'.
                Type '{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 290 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to type 'EpPropMergeType<(new (...args: any[]) => string | HTMLElement) | (() => string | HTMLElement) | ((new (...args: any[]) => string | HTMLElement) | (() => string | HTMLElement))[], unknown, unknown> | undefined'.
                  Type '{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 290 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to type 'HTMLElement'.
                    Types of property 'offsetParent' are incompatible.
                      Type '{ readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: ...; readonly length: number; item: (nameOrIndex?: string | undefined) => Element | ... 1 m...' is not assignable to type 'Element | null'.
                        Type '{ readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: ...; readonly length: number; item: (nameOrIndex?: string | undefined) => Element | ... 1 m...' is not assignable to type 'Element'.
                          Types of property 'attributes' are incompatible.
                            Type '{ [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: { readonly attributes: ...; ... 167 more ...; readonly assignedSlot: { ...; } | null; }; readonly length: number; ...' is not assignable to type 'NamedNodeMap'.
                              'number' index signatures are incompatible.
                                Type '{ readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: { readonly attributes: { [x: number]: ...; ... 8 more ...; [Symbol.iterator]: () => IterableIterator<...>; }; ... 167 more ...; r...' is not assignable to type 'Attr'.
                                  The types of 'ownerDocument.anchors' are incompatible between these types.
                                    Type '{ [x: number]: { charset: string; coords: string; download: string; hreflang: string; name: string; ping: string; referrerPolicy: string; rel: string; readonly relList: { [x: number]: string; readonly length: number; ... 13 more ...; [Symbol.iterator]: () => IterableIterator<...>; }; ... 317 more ...; username: stri...' is not assignable to type 'HTMLCollectionOf<HTMLAnchorElement>'.
                                      'number' index signatures are incompatible.
                                        Type '{ charset: string; coords: string; download: string; hreflang: string; name: string; ping: string; referrerPolicy: string; rel: string; readonly relList: { [x: number]: string; readonly length: number; value: string; ... 12 more ...; [Symbol.iterator]: () => IterableIterator<...>; }; ... 317 more ...; username: stri...' is not assignable to type 'HTMLAnchorElement'.
                                          Types of property 'shadowRoot' are incompatible.
                                            Type '{ readonly delegatesFocus: boolean; readonly host: { readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; ... 258 more ...; evaluate: (expression: string, contextNode: Node, resolver?: XPathNSRes...' is not assignable to type 'ShadowRoot | null'.
                                              Type '{ readonly delegatesFocus: boolean; readonly host: { readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; ... 258 more ...; evaluate: (expression: string, contextNode: Node, resolver?: XPathNSRes...' is not assignable to type 'ShadowRoot'.
                                                Types of property 'adoptedStyleSheets' are incompatible.
                                                  Type '{ readonly cssRules: { [x: number]: { cssText: string; readonly parentRule: ... | null; readonly parentStyleSheet: ... | null; readonly type: number; readonly STYLE_RULE: 1; readonly CHARSET_RULE: 2; ... 9 more ...; readonly FONT_FEATURE_VALUES_RULE: 14; }; readonly length: number; item: (index: number) => CSSRule |...' is not assignable to type 'CSSStyleSheet[]'.
                                                    Type '{ readonly cssRules: { [x: number]: { cssText: string; readonly parentRule: ... | null; readonly parentStyleSheet: ... | null; readonly type: number; readonly STYLE_RULE: 1; readonly CHARSET_RULE: 2; ... 9 more ...; readonly FONT_FEATURE_VALUES_RULE: 14; }; readonly length: number; item: (index: number) => CSSRule |...' is not assignable to type 'CSSStyleSheet'.
                                                      Types of property 'ownerNode' are incompatible.
                                                        Type '{ readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: ...; readonly length: number; item: (nameOrIndex?: string | undefined) => Element | ... 1 m...' is not assignable to type 'Element | ProcessingInstruction | null'.
                                                          Type '{ readonly attributes: { [x: number]: { readonly localName: string; readonly name: string; readonly namespaceURI: string | null; readonly ownerDocument: { readonly URL: string; alinkColor: string; readonly all: { [x: number]: ...; readonly length: number; item: (nameOrIndex?: string | undefined) => Element | ... 1 m...' is not assignable to type 'Element | ProcessingInstruction | null'.

130 const flatColumns = computed(() => flatColumnsFunc(tableColumns))
                                                       ~~~~~~~~~~~~

src/components/ProTable/index.vue:314:10 - error TS2345: Argument of type '{ align: string; reserveSelection: boolean; type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; ... 13 more ...; xl?: { ...; } | undefined; } | undefined; ... 44 more ...; filterOpened?: boolean | undefined; }' is not assignable to parameter of type 'Partial<{ type: string; width: string | number; minWidth: string | number; showOverflowTooltip: boolean | Partial<Pick<ElTooltipProps, "transition" | "effect" | "offset" | ... 7 more ... | "hideAfter">> | undefined; ... 4 more ...; filterMultiple: boolean; }> & Omit<...> & Record<...>'.
  Type '{ align: string; reserveSelection: boolean; type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; ... 13 more ...; xl?: { ...; } | undefined; } | undefined; ... 44 more ...; filterOpened?: boolean | undefined; }' is not assignable to type 'Partial<{ type: string; width: string | number; minWidth: string | number; showOverflowTooltip: boolean | Partial<Pick<ElTooltipProps, "transition" | "effect" | "offset" | ... 7 more ... | "hideAfter">> | undefined; ... 4 more ...; filterMultiple: boolean; }>'.
    Types of property 'showOverflowTooltip' are incompatible.
      Type 'boolean | { transition?: string | undefined; effect?: string | undefined; offset?: number | undefined; popperClass?: EpPropMergeType<(new (...args: any[]) => string | { [x: string]: boolean; } | (string | { ...; } | (string | ... 1 more ... | (string | ... 1 more ... | (string | ... 1 more ... | (string | ... 1 more...' is not assignable to type 'boolean | Partial<Pick<ElTooltipProps, "transition" | "effect" | "offset" | "popperClass" | "appendTo" | "showArrow" | "enterable" | "placement" | "popperOptions" | "showAfter" | "hideAfter">> | undefined'.

314         <el-table-column
             ~~~~~~~~~~~~~~~

src/components/ProTable/index.vue:343:68 - error TS2322: Type '{ type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; label?: string | undefined; ... 12 more ...; xl?: { ...; } | undefined; } | undefined; ... 46 more ...; filterOpened?: boolean | undefined; }' is not assignable to type 'ColumnProps<any>'.

343         <TableColumn v-if="!item.type && item.prop && item.isShow" :column="item">
                                                                       ~~~~~~~

  src/components/ProTable/components/TableColumn.vue:9:15
    9 defineProps<{ column: ColumnProps }>()
                    ~~~~~~
    The expected type comes from property 'column' which is declared here on type 'Partial<{}> & Omit<{ readonly column: ColumnProps<any>; } & VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<...>, never> & Record<...>'

src/components/ProTable/index.vue:375:46 - error TS2322: Type '{ type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; label?: string | undefined; ... 12 more ...; xl?: { ...; } | undefined; } | undefined; ... 46 more ...; filterOpened?: boolean | undefined; }[]' is not assignable to type 'ColumnProps<any>[]'.

375   <ColSetting v-if="toolButton" ref="colRef" v-model:col-setting="colSetting" />
                                                 ~~~~~~~~~~~~~~~~~~~

  src/components/ProTable/components/ColSetting.vue:9:15
    9 defineProps<{ colSetting: ColumnProps[] }>()
                    ~~~~~~~~~~
    The expected type comes from property 'colSetting' which is declared here on type 'Partial<{}> & Omit<{ readonly colSetting: ColumnProps<any>[]; } & VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<...>, never> & Record<...>'

src/hooks/useEcharts.ts:101:44 - error TS2345: Argument of type 'Ref<{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 290 more ...; focus: (options?: FocusOptions | undefined) => void; } | null>' is not assignable to parameter of type 'MaybeComputedElementRef<MaybeElement>'.
  Type 'Ref<{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 290 more ...; focus: (options?: FocusOptions | undefined) => void; } | null>' is not assignable to type 'Ref<MaybeElement>'.
    Type '{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 290 more ...; focus: (options?: FocusOptions | undefined) => void; } | null' is not assignable to type 'MaybeElement'.
      Type '{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 290 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to type 'MaybeElement'.
        Type '{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 290 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to type 'HTMLElement'.

101   const { width, height } = useElementSize(domRef, initialSize)
                                               ~~~~~~

src/hooks/useEcharts.ts:176:28 - error TS2345: Argument of type '{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 290 more ...; focus: (options?: FocusOptions | undefined) => void; } | null' is not assignable to parameter of type 'HTMLElement | null | undefined'.
  Type '{ accessKey: string; readonly accessKeyLabel: string; autocapitalize: string; dir: string; draggable: boolean; hidden: boolean; inert: boolean; innerText: string; lang: string; readonly offsetHeight: number; ... 290 more ...; focus: (options?: FocusOptions | undefined) => void; }' is not assignable to type 'HTMLElement'.

176       chart = echarts.init(domRef.value, chartTheme)
                               ~~~~~~~~~~~~

src/layouts/modules/Topbar/Toolbar/NavSearch/index.vue:17:106 - error TS2339: Property '$t' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { eventBus: Emitter<MittTypes>; settingsStore: Store<"settings", _UnwrapAll<Pick<{ settings: Ref<{ app: { colorScheme: "" | ... 1 more ... | "dark"; ... 6 more ...; translationLang: string; }; ... 8 more ...; copyright: { ...; }; }>; ... 10 more ...; upda...'.

17       <span class="text-sm text-stone-5 transition group-hover:text-dark dark:group-hover:text-white">{{ $t('head.search') }}</span>
                                                                                                            ~~

src/views/monitor/login_logs/index.vue:96:9 - error TS2322: Type '{ type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; label?: string | undefined; ... 12 more ...; xl?: { ...; } | undefined; } | undefined; ... 46 more ...; filterOpened?: boolean | undefined; }[]' is not assignable to type 'ColumnProps<any>[]'.

96         :columns="columns"
           ~~~~~~~~

  src/components/ProTable/index.vue:42:3
    42   columns: ColumnProps[] // 列配置项  ==> 必传
         ~~~~~~~
    The expected type comes from property 'columns' which is declared here on type 'Partial<{ border: boolean; rowKey: string; columns: ColumnProps<any>[]; searchCol: number | Record<BreakPoint, number>; requestAuto: boolean; isShowPageable: boolean; isShowSearch: boolean; initParam: any; toolButton: boolean | ("search" | ... 1 more ... | "setting")[]; }> & Omit<...> & Record<...>'

src/views/monitor/online_user/index.vue:79:9 - error TS2322: Type '{ type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; label?: string | undefined; ... 12 more ...; xl?: { ...; } | undefined; } | undefined; ... 46 more ...; filterOpened?: boolean | undefined; }[]' is not assignable to type 'ColumnProps<any>[]'.

79         :columns="columns"
           ~~~~~~~~

  src/components/ProTable/index.vue:42:3
    42   columns: ColumnProps[] // 列配置项  ==> 必传
         ~~~~~~~
    The expected type comes from property 'columns' which is declared here on type 'Partial<{ border: boolean; rowKey: string; columns: ColumnProps<any>[]; searchCol: number | Record<BreakPoint, number>; requestAuto: boolean; isShowPageable: boolean; isShowSearch: boolean; initParam: any; toolButton: boolean | ("search" | ... 1 more ... | "setting")[]; }> & Omit<...> & Record<...>'

src/views/monitor/operation_logs/index.vue:100:9 - error TS2322: Type '{ type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; label?: string | undefined; ... 12 more ...; xl?: { ...; } | undefined; } | undefined; ... 46 more ...; filterOpened?: boolean | undefined; }[]' is not assignable to type 'ColumnProps<any>[]'.

100         :columns="columns"
            ~~~~~~~~

  src/components/ProTable/index.vue:42:3
    42   columns: ColumnProps[] // 列配置项  ==> 必传
         ~~~~~~~
    The expected type comes from property 'columns' which is declared here on type 'Partial<{ border: boolean; rowKey: string; columns: ColumnProps<any>[]; searchCol: number | Record<BreakPoint, number>; requestAuto: boolean; isShowPageable: boolean; isShowSearch: boolean; initParam: any; toolButton: boolean | ("search" | ... 1 more ... | "setting")[]; }> & Omit<...> & Record<...>'

src/views/sys_setting/sys_resource/index.vue:87:84 - error TS2322: Type '{ type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; label?: string | undefined; ... 12 more ...; xl?: { ...; } | undefined; } | undefined; ... 46 more ...; filterOpened?: boolean | undefined; }[]' is not assignable to type 'ColumnProps<any>[]'.

87         ref="proTableRef" :border="false" title="资源管理" :request-api="getTableList" :columns="columns"
                                                                                      ~~~~~~~~

  src/components/ProTable/index.vue:42:3
    42   columns: ColumnProps[] // 列配置项  ==> 必传
         ~~~~~~~
    The expected type comes from property 'columns' which is declared here on type 'Partial<{ border: boolean; rowKey: string; columns: ColumnProps<any>[]; searchCol: number | Record<BreakPoint, number>; requestAuto: boolean; isShowPageable: boolean; isShowSearch: boolean; initParam: any; toolButton: boolean | ("search" | ... 1 more ... | "setting")[]; }> & Omit<...> & Record<...>'

src/views/sys_setting/sys_role/index.vue:93:9 - error TS2322: Type '{ type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; label?: string | undefined; ... 12 more ...; xl?: { ...; } | undefined; } | undefined; ... 46 more ...; filterOpened?: boolean | undefined; }[]' is not assignable to type 'ColumnProps<any>[]'.

93         :columns="columns"
           ~~~~~~~~

  src/components/ProTable/index.vue:42:3
    42   columns: ColumnProps[] // 列配置项  ==> 必传
         ~~~~~~~
    The expected type comes from property 'columns' which is declared here on type 'Partial<{ border: boolean; rowKey: string; columns: ColumnProps<any>[]; searchCol: number | Record<BreakPoint, number>; requestAuto: boolean; isShowPageable: boolean; isShowSearch: boolean; initParam: any; toolButton: boolean | ("search" | ... 1 more ... | "setting")[]; }> & Omit<...> & Record<...>'

src/views/sys_setting/sys_user/index.vue:106:9 - error TS2322: Type '{ type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; label?: string | undefined; ... 12 more ...; xl?: { ...; } | undefined; } | undefined; ... 46 more ...; filterOpened?: boolean | undefined; }[]' is not assignable to type 'ColumnProps<any>[]'.

106         :columns="columns"
            ~~~~~~~~

  src/components/ProTable/index.vue:42:3
    42   columns: ColumnProps[] // 列配置项  ==> 必传
         ~~~~~~~
    The expected type comes from property 'columns' which is declared here on type 'Partial<{ border: boolean; rowKey: string; columns: ColumnProps<any>[]; searchCol: number | Record<BreakPoint, number>; requestAuto: boolean; isShowPageable: boolean; isShowSearch: boolean; initParam: any; toolButton: boolean | ("search" | ... 1 more ... | "setting")[]; }> & Omit<...> & Record<...>'

src/views/welcome/modules/header_banner.vue:19:16 - error TS2339: Property '$t' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { userStore: Store<"user", _UnwrapAll<Pick<{ account: Ref<string>; token: Ref<string | null | undefined>; avatar: Ref<string>; ... 5 more ...; editPassword: (data: { ...; }) => Promise<...>; }, "account" | ... 2 more ... | "permissions">>, Pick<...>, Pick...'.

19             {{ $t('home.greeting', { userName: userStore.account }) }}
                  ~~

src/views/welcome/modules/header_banner.vue:21:75 - error TS2339: Property '$t' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { userStore: Store<"user", _UnwrapAll<Pick<{ account: Ref<string>; token: Ref<string | null | undefined>; avatar: Ref<string>; ... 5 more ...; editPassword: (data: { ...; }) => Promise<...>; }, "account" | ... 2 more ... | "permissions">>, Pick<...>, Pick...'.

21           <span class="text-emphasis text-16px text-#999 leading-30px">{{ $t('home.weatherDesc') }} </span>
                                                                             ~~

src/views/welcome/modules/table_statistics.vue:154:92 - error TS2322: Type '{ type?: TypeProps | undefined; tag?: boolean | undefined; isShow?: boolean | undefined; search?: { el?: SearchType | undefined; label?: string | undefined; ... 12 more ...; xl?: { ...; } | undefined; } | undefined; ... 46 more ...; filterOpened?: boolean | undefined; }[]' is not assignable to type 'ColumnProps<any>[]'.

154           :is-show-search="false" :border="false" title="资源管理" :request-api="getTableList" :columns="columns"
                                                                                               ~~~~~~~~

  src/components/ProTable/index.vue:42:3
    42   columns: ColumnProps[] // 列配置项  ==> 必传
         ~~~~~~~
    The expected type comes from property 'columns' which is declared here on type 'Partial<{ border: boolean; rowKey: string; columns: ColumnProps<any>[]; searchCol: number | Record<BreakPoint, number>; requestAuto: boolean; isShowPageable: boolean; isShowSearch: boolean; initParam: any; toolButton: boolean | ("search" | ... 1 more ... | "setting")[]; }> & Omit<...> & Record<...>'


Found 20 errors in 12 files.

Errors  Files
     4  src/components/FormDesign/core/components/designer/src/modules/editContainer/editScreenContainer.vue:17
     4  src/components/ProTable/index.vue:130
     2  src/hooks/useEcharts.ts:101
     1  src/layouts/modules/Topbar/Toolbar/NavSearch/index.vue:17
     1  src/views/monitor/login_logs/index.vue:96
     1  src/views/monitor/online_user/index.vue:79
     1  src/views/monitor/operation_logs/index.vue:100
     1  src/views/sys_setting/sys_resource/index.vue:87
     1  src/views/sys_setting/sys_role/index.vue:93
     1  src/views/sys_setting/sys_user/index.vue:106
     2  src/views/welcome/modules/header_banner.vue:19
     1  src/views/welcome/modules/table_statistics.vue:154
 ELIFECYCLE  Command failed with exit code 2.
(base) luojiwen@luojiwendeMacBook-Pro elegant-admin % 
![image](https://github.com/zhangyao1990/elegant-admin/assets/41353723/3f0b708d-0d4d-48a2-90f7-487949942fed)

**Comment by zhangyao1990** [comment]
你把pnpm-lock.yaml文件和node_modules删了，然后VSCode中切换typescript的版本，使用工作空间的版,看能否解决问题。
